language: haxe
haxe: development

os:
  - linux
  - osx

sudo: required
dist: trusty
osx_image: xcode8

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    sudo apt-get update -y;
    sudo apt-get install gcc-multilib -y;
    fi
  - make hl32lib

script:
  - haxe -hl src/_main.c -cp other/tests/helloworld -main HelloWorld -D interp
  - haxe -hl src/_main.c -cp other/tests/helloworld -main HelloWorld && make hlc32
