language: c

os:
  - linux
  - osx

sudo: required
dist: trusty
osx_image: xcode8

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    sudo apt-get update -y;
    sudo apt-get install gcc-multilib -y;
    fi

script:
  - make hl32lib
